plugins:
  - cleanupNumericValues: { floatPrecision: 1 }
  - cleanupIDs: true
  - collapseGroups: true
  - removeDesc: true
  - removeDimensions: false
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - removeRasterImages: true
  - removeStyleElement: true
  - removeTitle: true
  - removeUselessDefs: true
  - removeViewBox: false
