export const GET_FILTERS_REQUEST = "GET_FILTERS_REQUEST";
export const GET_FILTERS_SUCCESS = "GET_FILTERS_SUCCESS";
export const GET_FILTERS_ERROR = "GET_FILTERS_ERROR";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
export const TOGGLE_FILTERS_ALL = "TOGGLE_FILTERS_ALL";
export const SHOW_LESS_FILTERS = "SHOW_LESS_FILTERS";

export default {
  GET_FILTERS_REQUEST,
  GET_FILTERS_SUCCESS,
  GET_FILTERS_ERROR,
  TOGGLE_FILTERS,
  TOGGLE_FILTERS_ALL,
  SHOW_LESS_FILTERS,
};
