export const GET_GAMES_REQUEST = "GET_GAMES_REQUEST";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_ERROR = "GET_GAMES_ERROR";
export const GET_GAME_CARD_REQUEST = "GET_GAME_CARD_REQUEST";
export const GET_GAME_CARD_SUCCESS = "GET_GAME_CARD_SUCCESS";
export const GET_GAME_CARD_ERROR = "GET_GAME_CARD_REQUEST";
export const FILTER_GAMES = "FILTER_GAMES";
export const FILTER_BY_NAME = "FILTER_BY_NAME";

export default {
  GET_GAMES_REQUEST,
  GET_GAMES_SUCCESS,
  GET_GAMES_ERROR,
  GET_GAME_CARD_REQUEST,
  GET_GAME_CARD_SUCCESS,
  GET_GAME_CARD_ERROR,
  FILTER_GAMES,
  FILTER_BY_NAME,
};
