export const GET_GAMES_REQUEST = "GET_GAMES_REQUEST";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_ERROR = "GET_GAMES_ERROR";
export const FILTER_GAMES = "FILTER_GAMES";
export const GET_GAME_CARD_REQUEST = "GET_GAME_CARD_REQUEST";

export default {
  GET_GAMES_REQUEST,
  GET_GAMES_SUCCESS,
  GET_GAMES_ERROR,
  FILTER_GAMES,
  GET_GAME_CARD_REQUEST,
};
