const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
const GET_GAMES_ERROR = 'GET_GAMES_ERROR';
const FILTER_GAMES = 'FILTER_GAMES';
const GET_GAME_CARD_REQUEST = 'GET_GAME_CARD_REQUEST';

export {
  GET_GAMES_REQUEST,
  GET_GAMES_SUCCESS,
  GET_GAMES_ERROR,
  FILTER_GAMES,
  GET_GAME_CARD_REQUEST,
};
