export type BingoType = {
  go: Boolean;
  sunsetEnding: Boolean;
  healthMeat: Boolean;
  sleevelessJacket: Boolean;
  bossWithGun: Boolean;
  fireBombs: Boolean;
  twoWordTitle: Boolean;
  throwingKnife: Boolean;
  subwayStage: Boolean;
  exproWrestler: Boolean;
  steelPipe: Boolean;
  kindnappedFemale: Boolean;
  specialDrainsHealth: Boolean;
  oilDrums: Boolean;
  clowns: Boolean;
  yellowRedHealthBar: Boolean;
  dominatrix: Boolean;
  powerSpeedBalance: Boolean;
  elevatorScene: Boolean;
  mansionStage: Boolean;
  mohawks: Boolean;
  buildingSite: Boolean;
  fatCharginMen: Boolean;
  sharpSuits: Boolean;
  graffiti: Boolean;
};
